=== jgonzalezllado/3evalenguajemarca/OK/comandes.dtd
<!ELEMENT comandas (comanda*)>
<!ELEMENT comanda (numeroSerie, cantidad, peso?)>
<!ELEMENT numeroSerie (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== jgonzalezllado/3evalenguajemarca/OK/comandes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comandas SYSTEM "comandes.dtd">
<comandas>
  <comanda>
    <numeroSerie>001</numeroSerie>
    <cantidad>2</cantidad>
    <peso>0.5</peso>
  </comanda>
  <comanda>
    <numeroSerie>002</numeroSerie>
    <cantidad>1</cantidad>
  </comanda>
</comandas>
