=== jgonzalezllado/3evalenguajemarca/OK/ejercicio3.dtd
<!ELEMENT productes (producte+)>
  <!ELEMENT producte (ratoli | teclat | monitor)>
  <!ELEMENT ratoli (codi, nom?, descripcio?)>
  <!ELEMENT teclat (codi, nom?, descripcio?)>
  <!ELEMENT monitor (codi, nom?, descripcio?)>
  <!ELEMENT codi (#PCDATA)>
  <!ELEMENT nom (#PCDATA)>
  <!ELEMENT descripcio (#PCDATA)>

=== jgonzalezllado/3evalenguajemarca/OK/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productes SYSTEM "ejercicio3.dtd">
<productes>
    <producte>
      <ratoli>
        <codi>RAT-001</codi>
        <nom>Ratón inalámbrico</nom>
        <descripcio>Modelo ergonómico con 3 botones y rueda de desplazamiento</descripcio>
      </ratoli>
    </producte>
    <producte>
      <teclat>
        <codi>TEC-002</codi>
        <nom>Teclado multimedia</nom>
        <descripcio>Teclado de tamaño completo con teclas multimedia y teclado numérico</descripcio>
      </teclat>
    </producte>
    <producte>
      <monitor>
        <codi>MON-003</codi>
        <nom>Monitor LED 24"</nom>
        <descripcio>Resolución Full HD (1920x1080) y entradas HDMI y VGA</descripcio>
      </monitor>
    </producte>
  </productes>
