=== jgonzalezllado/3evalenguajemarca/OK/ejercicio8.dtd
<!ELEMENT operaciones (operacion+)>
<!ELEMENT operacion (titulosvendidos|tituloscomprados)>
<!ATTLIST operacion tipo (venta|compra) #REQUIRED>
<!ELEMENT titulosvendidos (titulo+, cantidad, entregado,importe)>
<!ELEMENT titulo (nombre, autor, precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT entregado (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>
<!ELEMENT tituloscomprados (titulo+, proveedor, fechaCompra)>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT fechaCompra (dia, mes, año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== jgonzalezllado/3evalenguajemarca/OK/ejercicio8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operaciones SYSTEM "ejercicio8.dtd">
<operaciones>
    <operacion tipo="venta">
      <titulosvendidos>
        <titulo>
          <nombre>Nombre del libro</nombre>
          <autor>Autor del libro</autor>
          <precio>10.99</precio>
        </titulo>
        <titulo>
          <nombre>Otro libro</nombre>
          <autor>Nombre del autor</autor>
          <precio>19.99</precio>
        </titulo>
        <cantidad>2</cantidad>
        <entregado>si</entregado>
        <importe moneda="USD">30.98</importe>
      </titulosvendidos>
    </operacion>
    
    <operacion tipo="compra">
      <tituloscomprados>
        <titulo>
          <nombre>Nombre del libro</nombre>
          <autor>Autor del libro</autor>
          <precio>8.50</precio>
        </titulo>
        <titulo>
          <nombre>Otro libro</nombre>
          <autor>Nombre del autor</autor>
          <precio>12.75</precio>
        </titulo>
        <proveedor>Nombre del proveedor</proveedor>
        <fechaCompra>
          <dia>28</dia>
          <mes>3</mes>
          <año>2023</año>
        </fechaCompra>
      </tituloscomprados>
    </operacion>
  </operaciones>
