=== jgonzalezllado/3evalenguajemarca/OK/llistaventes.dtd
<!ELEMENT llistaventes (venda+)>
<!ELEMENT venda (import, comprador, venedor, data?, codi_factura)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT venedor (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT codi_factura (#PCDATA)>
<!ATTLIST data any CDATA #IMPLIED>
<!ATTLIST data mes CDATA #IMPLIED>
<!ATTLIST data dia CDATA #IMPLIED>
<!ATTLIST codi_factura lletra CDATA #REQUIRED>
<!ATTLIST codi_factura numeros CDATA #REQUIRED>

=== jgonzalezllado/3evalenguajemarca/OK/e04.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistaventes SYSTEM "llistaventes.dtd">
<llistaventes>
  <venda>
    <import>100.50</import>
    <comprador>Pere Torres</comprador>
    <venedor>Joan Garcia</venedor>
    <data>28/03/2023</data>
    <codi_factura lletra="A" numeros="123456"/>
  </venda>
  <venda>
    <import>200.00</import>
    <comprador>Marta Lopez</comprador>
    <venedor>David Ruiz</venedor>
    <codi_factura lletra="ABCDEF" numeros="123456"/>
  </venda>
</llistaventes>
